apiVersion: v1
kind: Config
clusters:
  - name: docker-desktop
    cluster:
      server: https://127.0.0.1:6443
      insecure-skip-tls-verify: true
contexts:
  - name: docker-desktop
    context:
      cluster: docker-desktop
      user: docker-desktop
current-context: docker-desktop
preferences: {}
users:
  - name: docker-desktop
    user:
      # empty user is fine for docker-desktop when skipping TLS verification