apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: backstage
  namespace: flux-system
  labels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/part-of: platform
spec:
  interval: 1h
  url: https://backstage.github.io/charts