apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-prod
spec:
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-repo
  path: gitops/flux/cluster-config/prod
