---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-prod
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-repo
  path: gitops/flux/cluster-config/prod
  postBuild:
    substitute:
      ENV: prod

