---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-dev
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  wait: false  # Temporarily disable health check wait
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-repo
  path: gitops/flux/cluster-config/dev
  postBuild:
    substitute:
      ENV: dev
