apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../sources/helm/argo-helm.yaml
  - ../sources/helm/istio.yaml
  - ../sources/helm/ingress-nginx.yaml
  - ../sources/helm/jetstack.yaml
  - ../sources/helm/external-dns.yaml
  - ../sources/helm/prometheus-community.yaml
  - ../sources/helm/grafana.yaml
  - ../sources/helm/elastic.yaml
  - ../sources/helm/fluent.yaml
  - ../sources/helm/jaegertracing.yaml
  - ../../../platform/base/namespaces/namespaces.yaml
  - ../../../platform/base/rbac/platform-readonly-rbac.yaml
  - ../../../platform/base/network-policies/default-deny-example.yaml
  - ../../../platform/addons/ingress-nginx/helm-release.yaml
  - ../../../platform/addons/cert-manager/helm-release.yaml
  - ../../../platform/addons/istio/helm-release.yaml
  - ../../../platform/addons/prometheus-stack/helm-release.yaml
  - ../../../platform/addons/grafana/helm-release.yaml
  - ../../../platform/addons/logging/helm-release.yaml
  - ../../../platform/addons/external-dns/helm-release.yaml
  - ../../../platform/addons/tracing/helm-release.yaml
